services:
  - type: web
    name: fitcore-backend
    env: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python init_db.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: fitcore-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ACCESS_TOKEN_EXPIRES
        value: 86400

databases:
  - name: fitcore-db
    databaseName: fitcore
    user: fitcore
    plan: free
